# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/farhan15r/cluster-chumbucket.git
    targetRevision: main
    path: manifests/infra-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
