# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://projectcalico.docs.tigera.io/charts
      chart: crd.projectcalico.org.v1
      targetRevision: v3.32.2
      helm:
        releaseName: calico-crds
    - repoURL: https://projectcalico.docs.tigera.io/charts
      chart: tigera-operator
      targetRevision: v3.32.2
      helm:
        releaseName: calico
        valuesObject:
          installation:
            controlPlaneReplicas: 1
            calicoNetwork:
              linuxDataplane: BPF
              ipPools:
                - name: default-ipv4-ippool
                  allowedUses:
                    - Workload
                    - Tunnel
                  assignmentMode: Automatic
                  blockSize: 26
                  cidr: 10.64.0.0/12
                  disableBGPExport: false
                  disableNewAllocations: false
                  encapsulation: None
                  natOutgoing: Enabled
                  nodeSelector: all()
          kubernetesServiceEndpoint:
            host: cp.cluster01.local
            port: "6443"
          goldmane:
            enabled: false
          whisker:
            enabled: false
          apiServer:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
